<a href="https://colab.research.google.com/github/Fernando-JG/Plan_de_Formacion_PDI_PAS_2026/blob/main/Mod_1_26052026/02_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell" style="padding:1.5rem 0 2rem;">
  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:2px solid #1E3A8A;">
    <div style="flex:1;">
      <span style="display:inline-block;font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#0F766E;background:#CCFBF1;border:1px solid #5EEAD4;padding:3px 10px;border-radius:20px;margin-bottom:8px;">Plan de Formación PDI/PAS 2026</span>
      <div style="font-size:11px;color:#475569;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;">Formación para la investigación</div>
      <div style="font-size:11px;font-style:italic;color:#475569;margin-bottom:4px;">Módulo 2 — Pandas</div>
      <h1 style="font-size:24px;font-weight:700;color:#1E3A8A;line-height:1.2;margin:0;">Python: Programación de IA</h1>
      <div style="font-size:13px;color:#475569;">Edna Viviana Segura Alvarado · Hans Mauricio Carrillo Hernández · Universidad de La Rioja</div>
    </div>
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;flex-shrink:0;">
      <img src="https://github.com/ednavivianasegura/AccesoImages/blob/main/logoUR.png?raw=true" alt="Logo UR" style="width:72px;height:auto;">
      <div style="font-size:9px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;text-align:center;line-height:1.4;">Universidad<br>de La Rioja</div>
    </div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-bottom:14px;">
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-list-check" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Contenidos</div>
      <div style="display:flex;flex-direction:column;gap:5px;">
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">1</span>Series y DataFrames</div>
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">2</span>Métodos y atributos</div>
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">3</span>Filtros y selección</div>
        <div style="font-size:12.5px;color:#1e293b;display:flex;align-items:center;gap:8px;"><span style="display:inline-flex;align-items:center;justify-content:center;width:18px;height:18px;border-radius:50%;background:#EFF6FF;border:1px solid #BFDBFE;color:#1E3A8A;font-size:10px;font-weight:600;flex-shrink:0;">4</span>Concatenación y merge</div>
      </div>
    </div>
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-target" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Objetivo</div>
      <div style="font-size:12.5px;color:#1e293b;line-height:1.6;">Manejar y analizar datos tabulares con <strong style="color:#1E3A8A;">pandas</strong>, aplicando filtros, transformaciones y combinaciones de DataFrames sobre conjuntos de datos reales.</div>
    </div>
  </div>
  <div style="display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;font-size:11px;color:#94A3B8;">
    <span><i class="ti ti-school" style="font-size:12px;color:#1E3A8A;"></i> Universidad de La Rioja — Logroño, La Rioja</span>
    <span><i class="ti ti-calendar" style="font-size:12px;color:#1E3A8A;"></i> Plan de Formación PDI/PAS 2026</span>
  </div>
</div>

In [150]:
!git clone https://github.com/ednavivianasegura/Plan_de_Formacion_PDI_PAS_2026.git

fatal: destination path 'Plan_de_Formacion_PDI_PAS_2026' already exists and is not an empty directory.

In [151]:
import os
file_path=("/content/Plan_de_Formacion_PDI_PAS_2026/")

In [5]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <div style="display:flex;align-items:center;gap:12px;margin-bottom:1rem;">
    <h2 class="nb-title">pandas</h2>
    <span class="nb-badge">Librería Esencial</span>
  </div>
  <hr class="nb-divider">
  <div class="nb-body">
    <p><code class="ic">pandas</code> es una de las librerías más utilizadas para el análisis de datos en Python. Proporciona estructuras de datos eficientes para trabajar con grandes volúmenes de información de forma sencilla.</p>
  </div>
  <div class="grid2">
    <div class="card">
      <div class="card-title"><i class="ti ti-vector" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Series</div>
      <div class="card-body">Arreglo de <strong>una dimensión</strong>, similar a un array de NumPy o una lista. Cada elemento tiene un índice asociado.</div>
    </div>
    <div class="card">
      <div class="card-title"><i class="ti ti-table" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;DataFrame</div>
      <div class="card-body">Estructura <strong>bidimensional</strong> similar a una tabla de Excel o base de datos SQL. Está conformada por <code class="ic">Series</code>.</div>
    </div>
  </div>
  <div class="code-block">
    <div class="code-header">
      <div class="dots"><div class="dot dot-r"></div><div class="dot dot-y"></div><div class="dot dot-g"></div></div>
      <span class="code-lang">Python</span>
    </div>
    <pre class="cc"><span class="kw">import</span> <span class="mod">pandas</span> <span class="kw">as</span> <span class="al">pd</span>  <span class="cm"># Convención estándar en la comunidad</span></pre>
  </div>
</div>

In [152]:
import numpy as np
import pandas as pd

In [7]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
  .tip-word{color:#1E3A8A;font-weight:600;border-bottom:1.5px dashed #1E3A8A;cursor:help;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Series</h3>
  <hr class="nb-divider">
  <div class="nb-body">
    <p>Una <code class="ic">Series</code> es un arreglo unidimensional con etiquetas de índice.
    Para inicializarla necesita un
    <span class="tip">
      <span class="tip-word">objeto iterable</span>
      <span class="tt">
        Cualquier objeto de Python que se puede recorrer elemento a elemento.
        Si puedes recorrerlo con un <code style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">for</code>, es iterable.
      </span>
    </span>.
    </p>
  </div>

  <div class="nb-note" style="margin-top:.8rem;">
    <i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="nb-note-text">Para explorar todos los métodos y atributos disponibles: <code class="ic">[i for i in dir(pd.Series()) if not i.startswith("_")]</code></span>
  </div>
</div>

In [8]:
#Serie Vacía
print(pd.Series([], dtype="float64"))

Series([], dtype: float64)

In [9]:
serie = pd.Series(["a", "b", "c", "d"], name="letras")
serie

0    a
1    b
2    c
3    d
Name: letras, dtype: object

In [10]:
# 1
# Para explorar cuántos métodos y atributos hay disponibles:
len([i for i in dir(pd.Series()) if not i.startswith("_")])

206

In [11]:
# 2
# Para explorar todos los métodos y atributos disponibles:

In [12]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">DataFrame</h3>
  <hr class="nb-divider">
  <div class="nb-body">
    <p>Un <code class="ic">DataFrame</code> es una estructura bidimensional de filas y columnas. Las filas se identifican con un índice y las columnas con un nombre. Los elementos pueden ser enteros, booleanos, cadenas, listas, tuplas…</p>
  </div>
  <p style="font-size:12px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.8rem;">Fuentes de creación</p>
  <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:1rem;">

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">list()</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;top:calc(100% + 6px);left:0;width:220px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">list()</strong> — lista de Python. Se pasa directamente a <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.DataFrame(lista)</span>
      <div style="position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">dict()</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;top:calc(100% + 6px);left:0;width:220px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">dict()</strong> — diccionario Python. Las llaves se convierten en columnas: <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.DataFrame(dic)</span>
      <div style="position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">.csv</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;top:calc(100% + 6px);left:0;width:220px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">.csv</strong> — archivo de texto con valores separados por comas. Se carga con <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.read_csv()</span>
      <div style="position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">.xlsx</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;top:calc(100% + 6px);left:0;width:220px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">.xlsx</strong> — archivo Excel. Se carga con <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.read_excel()</span>
      <div style="position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">np.arrays()</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;top:calc(100% + 6px);left:0;width:220px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">np.arrays()</strong> — array de NumPy. Se convierte directamente con <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.DataFrame(array)</span>
      <div style="position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">JSON</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;bottom:calc(100% + 6px);left:0;width:240px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">JSON</strong> — formato de texto ligero para intercambio de datos. Se carga con <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.read_json()</span>
      <div style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></div>
    </div>
  </div>

  <div style="position:relative;">
    <div style="background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;padding:8px 12px;font-family:monospace;font-size:12px;color:#1E3A8A;text-align:center;cursor:help;"
         onmouseover="this.nextElementSibling.style.visibility='visible';this.nextElementSibling.style.opacity='1'"
         onmouseout="this.nextElementSibling.style.visibility='hidden';this.nextElementSibling.style.opacity='0'">SQL</div>
    <div style="visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:8px 12px;position:absolute;z-index:999;bottom:calc(100% + 6px);left:0;width:240px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;">
      <strong style="color:#7dd3fc;">SQL</strong> — tablas de bases de datos relacionales. Se carga con <span style="font-family:monospace;background:#334155;padding:1px 5px;border-radius:3px;">pd.read_sql(query, conn)</span> pasando una conexión a la base de datos.
      <div style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></div>
    </div>
  </div>

</div>

</div>

In [13]:
# DataFrame vacío
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [18]:
# 3
# Desde lista
lista = list(range(100, 105))
print(lista)
df = pd.DataFrame()
df['lista']=lista
lista

[100, 101, 102, 103, 104]

[100, 101, 102, 103, 104]

In [19]:
# Desde lista de listas
lista = [[1,2,3],
         [4,5,6],
         [7,8,9]]

lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
# 4
# Se puede agregar el nombre de las columnas con el parametro "columns"
pd.DataFrame(lista,columns=['col1','col2','col3'])

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [25]:
# 5
# Desde diccionario por comprehensión
diccionario = {num: l for num, l in enumerate("abcdefg", start=10)}
# enumerate recorre el string "abcdefg" letra a letra asignando un contador.
# El parámetro start=10 hace que el contador empiece en 10 en lugar de 0:
pd.DataFrame(diccionario.items())

    0  1
0  10  a
1  11  b
2  12  c
3  13  d
4  14  e
5  15  f
6  16  g

In [26]:
# Se puede agregar el nombre de las columnas con el parametro "columns"
pd.DataFrame(diccionario.items(), columns = ["num", "letra"])

   num letra
0   10     a
1   11     b
2   12     c
3   13     d
4   14     e
5   15     f
6   16     g

In [28]:
# Desde archivos
pd.read_csv(file_path+"Data/iris.csv") # dirección del path establecida con anterioridad: file_path. Con el + se concatena el texto

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0             5.1           3.5           1.4           0.2     Iris-setosa
1             4.9           3.0           1.4           0.2     Iris-setosa
2             4.7           3.2           1.3           0.2     Iris-setosa
3             4.6           3.1           1.5           0.2     Iris-setosa
4             5.0           3.6           1.4           0.2     Iris-setosa
..            ...           ...           ...           ...             ...
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [29]:
# Crear un pd.DataFrame() a partir de un .xlsx

pd.read_excel(file_path+"Data/iris.xlsx")

# pandas toma la primera linea del .xlsx como cabecera y la usa como los nombres de las columnas

     Largo Sepalo   Ancho Sepalo   Largo Petalo   Ancho Petalo           Clase
0             5.1            3.5            1.4            0.2     Iris-setosa
1             4.9            3.0            1.4            0.2     Iris-setosa
2             4.7            3.2            1.3            0.2     Iris-setosa
3             4.6            3.1            1.5            0.2     Iris-setosa
4             5.0            3.6            1.4            0.2     Iris-setosa
..            ...            ...            ...            ...             ...
145           6.7            3.0            5.2            2.3  Iris-virginica
146           6.3            2.5            5.0            1.9  Iris-virginica
147           6.5            3.0            5.2            2.0  Iris-virginica
148           6.2            3.4            5.4            2.3  Iris-virginica
149           5.9            3.0            5.1            1.8  Iris-virginica

[150 rows x 5 columns]

In [30]:
# Vamos a guardar el DataFrame en la variable df para ver que atributos y metodos tiene.

df = pd.read_csv(file_path+"Data/iris.csv")

df

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0             5.1           3.5           1.4           0.2     Iris-setosa
1             4.9           3.0           1.4           0.2     Iris-setosa
2             4.7           3.2           1.3           0.2     Iris-setosa
3             4.6           3.1           1.5           0.2     Iris-setosa
4             5.0           3.6           1.4           0.2     Iris-setosa
..            ...           ...           ...           ...             ...
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [31]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Métodos de exploración</h3>
  <hr class="nb-divider">
  <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método / Atributo</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <tr><td><span class="tip"><code class="ic">.head(n)</code><span class="tt">Por defecto n=5. Útil para ver la estructura del DataFrame sin cargarlo completo.</span></span></td><td class="desc">Muestra las primeras <strong>n</strong> filas (por defecto 5)</td></tr>
        <tr><td><span class="tip"><code class="ic">.tail(n)</code><span class="tt">Por defecto n=5. Útil para verificar que el final del dataset es correcto.</span></span></td><td class="desc">Muestra las últimas <strong>n</strong> filas (por defecto 5)</td></tr>
        <tr><td><span class="tip"><code class="ic">.shape</code><span class="tt">Devuelve una tupla (filas, columnas). Mismo comportamiento que en NumPy.</span></span></td><td class="desc">Tupla con el número de filas y columnas</td></tr>
        <tr><td><span class="tip"><code class="ic">.index</code><span class="tt">Por defecto es un RangeIndex(start=0, stop=n, step=1).</span></span></td><td class="desc">Retorna el índice del DataFrame</td></tr>
        <tr><td><span class="tip"><code class="ic">.columns</code><span class="tt">Devuelve un Index con los nombres de las columnas.</span></span></td><td class="desc">Retorna los nombres de las columnas</td></tr>
        <tr><td><span class="tip"><code class="ic">.info()</code><span class="tt">Muestra tipo de dato por columna, valores no nulos y uso de memoria.</span></span></td><td class="desc">Información general del DataFrame</td></tr>
        <tr><td><span class="tip"><code class="ic">.dtypes</code><span class="tt">Devuelve el tipo de dato de cada columna como una Serie.</span></span></td><td class="desc">Tipo de dato de cada columna</td></tr>
      </tbody>
    </table>
  </div>
  <div class="hint"><i class="ti ti-info-circle" style="font-size:13px;"></i> Pasa el cursor sobre cada método para ver detalles.</div>
</div>

In [32]:
# 6
# Mostrar los primeros 10 elementos del dataset
df.head(10)

   Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
0           5.1           3.5           1.4           0.2  Iris-setosa
1           4.9           3.0           1.4           0.2  Iris-setosa
2           4.7           3.2           1.3           0.2  Iris-setosa
3           4.6           3.1           1.5           0.2  Iris-setosa
4           5.0           3.6           1.4           0.2  Iris-setosa
5           5.4           3.9           1.7           0.4  Iris-setosa
6           4.6           3.4           1.4           0.3  Iris-setosa
7           5.0           3.4           1.5           0.2  Iris-setosa
8           4.4           2.9           1.4           0.2  Iris-setosa
9           4.9           3.1           1.5           0.1  Iris-setosa

In [36]:
# 7
# Mostrar los últimos 10 elementos del dataset
df.tail(10) #por defecto, 5; si ponemos número, ese número de elementos

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
140           6.7           3.1           5.6           2.4  Iris-virginica
141           6.9           3.1           5.1           2.3  Iris-virginica
142           5.8           2.7           5.1           1.9  Iris-virginica
143           6.8           3.2           5.9           2.3  Iris-virginica
144           6.7           3.3           5.7           2.5  Iris-virginica
145           6.7           3.0           5.2           2.3  Iris-virginica
146           6.3           2.5           5.0           1.9  Iris-virginica
147           6.5           3.0           5.2           2.0  Iris-virginica
148           6.2           3.4           5.4           2.3  Iris-virginica
149           5.9           3.0           5.1           1.8  Iris-virginica

In [37]:
# 8
# Mostrar la información del dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Largo Sepalo  150 non-null    float64
 1   Ancho Sepalo  150 non-null    float64
 2   Largo Petalo  150 non-null    float64
 3   Ancho Petalo  150 non-null    float64
 4   Clase         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [39]:
# 9
# Mostrar el tipo de dato de cada columna
df.dtypes

Largo Sepalo    float64
Ancho Sepalo    float64
Largo Petalo    float64
Ancho Petalo    float64
Clase            object
dtype: object

In [40]:
# 10
# Mostrar los índices del dataset
df.index

RangeIndex(start=0, stop=150, step=1)

In [41]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Métodos estadísticos</h3>
  <hr class="nb-divider">
  <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <tr><td><span class="tip"><code class="ic">.describe()</code><span class="tt">Incluye count, mean, std, min, 25%, 50%, 75%, max para columnas numéricas.</span></span></td><td class="desc">Estadísticas descriptivas de las columnas numéricas</td></tr>
        <tr><td><span class="tip"><code class="ic">.count()</code><span class="tt">No cuenta los NaN. Útil para detectar valores faltantes por columna.</span></span></td><td class="desc">Número de elementos <strong>no NaN</strong> por columna</td></tr>
        <tr><td><span class="tip"><code class="ic">.sum()</code><span class="tt">axis=0 suma por columna (defecto), axis=1 suma por fila. Solo aplica a columnas numéricas.</span></span></td><td class="desc">Suma de cada columna. Con <code class="ic">axis=1</code> suma por filas</td></tr>
        <tr><td><span class="tip"><code class="ic">.cumsum()</code><span class="tt">Devuelve un DataFrame del mismo tamaño con la suma acumulada en cada posición.</span></span></td><td class="desc">Suma acumulada</td></tr>
        <tr><td><span class="tip"><code class="ic">.min()</code><span class="tt">Para columnas de texto devuelve el valor mínimo según orden alfabético.</span></span></td><td class="desc">Valor mínimo de cada columna</td></tr>
        <tr><td><span class="tip"><code class="ic">.max()</code><span class="tt">Para columnas de texto devuelve el valor máximo según orden alfabético.</span></span></td><td class="desc">Valor máximo de cada columna</td></tr>
        <tr><td><span class="tip"><code class="ic">.mean()</code><span class="tt">Solo aplica a columnas numéricas. Usa df.iloc[:, :-1].mean() para excluir la última columna.</span></span></td><td class="desc">Media aritmética de cada columna numérica</td></tr>
        <tr><td><span class="tip"><code class="ic">.median()</code><span class="tt">El valor central de los datos ordenados. Más robusta que la media ante valores atípicos.</span></span></td><td class="desc">Mediana de cada columna numérica</td></tr>
      </tbody>
    </table>
  </div>
  <div class="hint"><i class="ti ti-info-circle" style="font-size:13px;"></i> Pasa el cursor sobre cada método para ver detalles adicionales.</div>
</div>

In [42]:
# 11
# .describe() muestra la descripción estadística del DataFrame, retorna un pd.DataFrame()
df.describe()

       Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo
count    150.000000    150.000000    150.000000    150.000000
mean       5.843333      3.054000      3.758667      1.198667
std        0.828066      0.433594      1.764420      0.763161
min        4.300000      2.000000      1.000000      0.100000
25%        5.100000      2.800000      1.600000      0.300000
50%        5.800000      3.000000      4.350000      1.300000
75%        6.400000      3.300000      5.100000      1.800000
max        7.900000      4.400000      6.900000      2.500000

In [43]:
# 12
# .count() cuenta el número de elementos que no son NaN de cada columna
df.count()

Largo Sepalo    150
Ancho Sepalo    150
Largo Petalo    150
Ancho Petalo    150
Clase           150
dtype: int64

In [44]:
# 13
# .sum() retorna la suma de cada columna de sus elementos (Solo aplica para columnas que se puedan sumar)
df.sum() #suma las variables numércias, las otras las concatena como viene abajo

Largo Sepalo                                                876.5
Ancho Sepalo                                                458.1
Largo Petalo                                                563.8
Ancho Petalo                                                179.8
Clase           Iris-setosaIris-setosaIris-setosaIris-setosaIr...
dtype: object

In [46]:
# 14
# .min() muestra el minimo de cada columna
df.min() # en clase da el mínimo en orden alfabético

Largo Sepalo            4.3
Ancho Sepalo            2.0
Largo Petalo            1.0
Ancho Petalo            0.1
Clase           Iris-setosa
dtype: object

In [47]:
# 15
# .max() muestra el maximo de cada columna
df.max()

Largo Sepalo               7.9
Ancho Sepalo               4.4
Largo Petalo               6.9
Ancho Petalo               2.5
Clase           Iris-virginica
dtype: object

In [48]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Selección e indexado</h3>
  <hr class="nb-divider">
  <div class="table-wrap">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
      <tbody>
        <!-- Filas 1, 2, 3 → tooltip hacia ABAJO (por defecto) -->
        <tr><td><span class="tip"><code class="ic">df["col"]</code><span class="tt">Devuelve la columna como una Serie. Para varias columnas: df[["col1","col2"]]</span></span></td><td class="desc">Selecciona una columna por nombre</td></tr>
        <tr><td><span class="tip"><code class="ic">df[["c1","c2"]]</code><span class="tt">Pasar una lista de nombres devuelve un DataFrame, no una Serie.</span></span></td><td class="desc">Selecciona múltiples columnas</td></tr>
        <tr><td><span class="tip"><code class="ic">.iloc[fila, col]</code><span class="tt">Indexado por posición numérica, igual que NumPy. iloc[2, 3] = fila 2, columna 3.</span></span></td><td class="desc">Acceso por <strong>posición</strong> (índice numérico)</td></tr>

        <!-- Filas 4, 5, 6 → tooltip hacia ARRIBA -->
        <tr><td><span class="tip"><code class="ic">.loc[idx, "col"]</code><span class="tt" style="top:auto;bottom:calc(100% + 6px);">Indexado por etiqueta. Si el índice es numérico, loc[0] y iloc[0] dan el mismo resultado.<span style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></span></span></span></td><td class="desc">Acceso por <strong>etiqueta</strong> (nombre de índice/columna)</td></tr>
        <tr><td><span class="tip"><code class="ic">.at[idx, "col"]</code><span class="tt" style="top:auto;bottom:calc(100% + 6px);">Más rápido que .loc para acceder a un solo valor. Permite sobreescribir el valor.<span style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></span></span></span></td><td class="desc">Acceso a un <strong>único valor</strong> — permite sobreescribir</td></tr>
        <tr><td><span class="tip"><code class="ic">.iat[fila, col]</code><span class="tt" style="top:auto;bottom:calc(100% + 6px);">Versión posicional de .at. Equivale a df["col"].iat[n].<span style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></span></span></span></td><td class="desc">Acceso a un <strong>único valor</strong> por posición</td></tr>
        </tbody>
    </table>
  </div>

</div>

In [49]:
# .sum(axis = 1) retorna la suma horizantal de cada fila
# Por defecto axis = 0
print(df.head(5))
print("--"*50)
print("Suma horizontal:\n")
print(df.iloc[:, :-1].sum(axis = 1).head(5)) #todas las filas, pero columnas todas menos la última

   Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
0           5.1           3.5           1.4           0.2  Iris-setosa
1           4.9           3.0           1.4           0.2  Iris-setosa
2           4.7           3.2           1.3           0.2  Iris-setosa
3           4.6           3.1           1.5           0.2  Iris-setosa
4           5.0           3.6           1.4           0.2  Iris-setosa
----------------------------------------------------------------------------------------------------
Suma horizontal:

0    10.2
1     9.5
2     9.4
3     9.4
4    10.2
dtype: float64

In [62]:
 # 16
 # .mean() muestra la media de cada columna numércia
 df.iloc[:,:-1].mean()
 # df.iloc[:,i if i != "Clase"].mean()

Largo Sepalo    5.843333
Ancho Sepalo    3.054000
Largo Petalo    3.758667
Ancho Petalo    1.198667
dtype: float64

In [61]:
df.loc[:, df.columns != 'Clase'].mean()

Largo Sepalo    5.843333
Ancho Sepalo    3.054000
Largo Petalo    3.758667
Ancho Petalo    1.198667
dtype: float64

Largo Sepalo    5.843333
Ancho Sepalo    3.054000
Largo Petalo    3.758667
Ancho Petalo    1.198667
dtype: float64

In [ ]:
# 17
# .median() muestra la mediana de cada columna
# La mediana es el valor que ocupa el lugar central de todos los datos cuando éstos están ordenados de menor a mayor.

In [53]:
# .cumsum() Suma acumulada

print(df.head(5))
print("--"*50)
print("Suma acumulada:\n")


print(df.iloc[:, :-1].cumsum().head(5))

   Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo        Clase
0           5.1           3.5           1.4           0.2  Iris-setosa
1           4.9           3.0           1.4           0.2  Iris-setosa
2           4.7           3.2           1.3           0.2  Iris-setosa
3           4.6           3.1           1.5           0.2  Iris-setosa
4           5.0           3.6           1.4           0.2  Iris-setosa
----------------------------------------------------------------------------------------------------
Suma acumulada:

   Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo
0           5.1           3.5           1.4           0.2
1          10.0           6.5           2.8           0.4
2          14.7           9.7           4.1           0.6
3          19.3          12.8           5.6           0.8
4          24.3          16.4           7.0           1.0

In [54]:
# Para seleccionar una columna podemos hacer "indexing"
df["Largo Sepalo"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Largo Sepalo, Length: 150, dtype: float64

In [ ]:
df["Clase"]

In [ ]:
# Si quiero seleccionario varias columnas debo pasar una lista de columnas
df[["Largo Sepalo", "Ancho Petalo", "Clase"]].head(3)

In [ ]:
# Si quiero el elemento de indice 2 de la columna "Largo Sepalo"

df["Largo Sepalo"][2]

In [ ]:
# Existe un método .iat que hace lo mismo (index at)

df["Largo Sepalo"].iat[2] #Accede al elemento en la posición 2 (tercera fila, ya que el índice empieza en 0)
# de esa Serie. Devuelve un único valor escalar.

In [ ]:
# También podemos usar el método .iloc
# Con .iloc debemos darle las coordenadas, como si se tratara de una matriz

df.iloc[2, 3]

In [ ]:
# Si queremos usar el indice + el nombre de la columna podemos usar .at
# Este método nos deja sobreescribir valores dentro del DataFrame

df.at[0, "Largo Sepalo"] #A diferencia de .loc que solo lee, .at permite tanto leer como modificar
# SOBREESCRIBIR — cambiar el valor
# por ejemplo: df.at[0, "Largo Sepalo"] = 99.9

In [ ]:
# También podemos usar .loc que nos da el mismo resultado
# Este método NO nos deja sobreescribir valores dentro del DataFrame

df.loc[0, "Largo Sepalo"]

In [ ]:
#La diferencia clave es el criterio de acceso:
#.iloc accede por posición numérica — como los índices de una lista, siempre empezando desde 0:
#df.iloc[0]      # primera fila (posición 0)
#df.iloc[2, 3]   # fila en posición 2, columna en posición 3
#df.iloc[0:3]    # filas en posiciones 0, 1 y 2

# .loc accede por etiqueta — el nombre real del índice o de la columna:
# df.loc[0]               # fila cuyo índice se llama 0
# df.loc[0, "Edad"]       # fila índice 0, columna llamada "Edad"
# df.loc[0:3]             # filas desde etiqueta 0 hasta 3 (ambas incluidas)

# Si el DataFrame tiene índice ["a", "b", "c", "d"]
#df.iloc[0]    # devuelve la fila "a" — primera posición
#df.loc["c"]   # devuelve la fila "c" — por etiqueta

# Si el índice numérico empieza en 5: [5, 6, 7, 8]
#df.iloc[0]    # devuelve la fila con índice 5 — primera posición
#df.loc[5]     # devuelve la fila con índice 5 — por etiqueta
#df.loc[0]     # KeyError — no existe etiqueta 0

In [63]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Ordenar, resetear índice y eliminar</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    Estas operaciones <strong>no son in-place</strong> por defecto — devuelven un nuevo DataFrame sin modificar el original. Para modificar en el lugar añade <code class="ic">inplace=True</code>.
  </div>

  <div class="warn-box" style="margin-top:.8rem;">
    <i class="ti ti-alert-triangle" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="warn-text">Si la fila o columna no existe, <code class="ic">.drop()</code> lanza un <code class="ic">KeyError</code>. Usa <code class="ic">errors="ignore"</code> para evitarlo.</span>
  </div>
</div>

In [64]:
# .sort_values(column) ordena los valores del DataFrame usando como referencia una o varias columnas
# Por defecto ordena de menor a mayor
# Esta operación no es in-place

df.sort_values("Largo Sepalo")

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
122           7.7           2.8           6.7           2.0  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [65]:
# Ordenando por varias columnas

df.sort_values(["Largo Sepalo", "Largo Petalo"])

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
13            4.3           3.0           1.1           0.1     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
41            4.5           2.3           1.3           0.3     Iris-setosa
..            ...           ...           ...           ...             ...
135           7.7           3.0           6.1           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
131           7.9           3.8           6.4           2.0  Iris-virginica

[150 rows x 5 columns]

In [66]:
# Ordenando de mayor a menor

df.sort_values(["Largo Sepalo", "Largo Petalo"], ascending = False)

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
131           7.9           3.8           6.4           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
..            ...           ...           ...           ...             ...
41            4.5           2.3           1.3           0.3     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
13            4.3           3.0           1.1           0.1     Iris-setosa

[150 rows x 5 columns]

In [68]:
# Si queremos que sea in-place podemos cambiar un parametro

df.sort_values(["Largo Sepalo", "Largo Petalo"], ascending = False, inplace = True)

In [69]:
print(df)

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
131           7.9           3.8           6.4           2.0  Iris-virginica
118           7.7           2.6           6.9           2.3  Iris-virginica
117           7.7           3.8           6.7           2.2  Iris-virginica
122           7.7           2.8           6.7           2.0  Iris-virginica
135           7.7           3.0           6.1           2.3  Iris-virginica
..            ...           ...           ...           ...             ...
41            4.5           2.3           1.3           0.3     Iris-setosa
8             4.4           2.9           1.4           0.2     Iris-setosa
38            4.4           3.0           1.3           0.2     Iris-setosa
42            4.4           3.2           1.3           0.2     Iris-setosa
13            4.3           3.0           1.1           0.1     Iris-setosa

[150 rows x 5 columns]

In [71]:
# 18
# .reset_index() resetea el indice
# Crea una columna nueva con el indice anterior
# Esta operación no es in-place

df.reset_index()

,index,Largo Sepalo,Ancho Sepalo,Largo Petalo,Ancho Petalo,Clase
0,131,7.9,3.8,6.4,2.0,Iris-virginica
1,118,7.7,2.6,6.9,2.3,Iris-virginica
2,117,7.7,3.8,6.7,2.2,Iris-virginica
3,122,7.7,2.8,6.7,2.0,Iris-virginica
4,135,7.7,3.0,6.1,2.3,Iris-virginica
...,...,...,...,...,...,...
145,41,4.5,2.3,1.3,0.3,Iris-setosa
146,8,4.4,2.9,1.4,0.2,Iris-setosa
147,38,4.4,3.0,1.3,0.2,Iris-setosa
148,42,4.4,3.2,1.3,0.2,Iris-setosa
149,13,4.3,3.0,1.1,0.1,Iris-setosa

In [72]:
# Si no queremos que se cree esa nueva columna podemos agregar al método

df.reset_index(drop = True)

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0             7.9           3.8           6.4           2.0  Iris-virginica
1             7.7           2.6           6.9           2.3  Iris-virginica
2             7.7           3.8           6.7           2.2  Iris-virginica
3             7.7           2.8           6.7           2.0  Iris-virginica
4             7.7           3.0           6.1           2.3  Iris-virginica
..            ...           ...           ...           ...             ...
145           4.5           2.3           1.3           0.3     Iris-setosa
146           4.4           2.9           1.4           0.2     Iris-setosa
147           4.4           3.0           1.3           0.2     Iris-setosa
148           4.4           3.2           1.3           0.2     Iris-setosa
149           4.3           3.0           1.1           0.1     Iris-setosa

[150 rows x 5 columns]

In [73]:
# Para hacer esta operación in-place podemos cambiar un parametro

df.reset_index(drop = True, inplace = True)

In [74]:
df

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0             7.9           3.8           6.4           2.0  Iris-virginica
1             7.7           2.6           6.9           2.3  Iris-virginica
2             7.7           3.8           6.7           2.2  Iris-virginica
3             7.7           2.8           6.7           2.0  Iris-virginica
4             7.7           3.0           6.1           2.3  Iris-virginica
..            ...           ...           ...           ...             ...
145           4.5           2.3           1.3           0.3     Iris-setosa
146           4.4           2.9           1.4           0.2     Iris-setosa
147           4.4           3.0           1.3           0.2     Iris-setosa
148           4.4           3.2           1.3           0.2     Iris-setosa
149           4.3           3.0           1.1           0.1     Iris-setosa

[150 rows x 5 columns]

In [ ]:
# 19
# Eliminar filas o columnas
# Para esto tenemos el método .drop()
# Toma como parametro las filas/columnas que queremos eliminar
# Si quiero eliminar filas debo agregar axis = 0
# Si quiero eliminar columnas debo agregar axis = 1
# Esta operación no es in-place
# por defecto se eliminan filas

#Eliminar fila 2 del dataset

In [75]:
df.drop("Clase", axis = 1)

     Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo
0             7.9           3.8           6.4           2.0
1             7.7           2.6           6.9           2.3
2             7.7           3.8           6.7           2.2
3             7.7           2.8           6.7           2.0
4             7.7           3.0           6.1           2.3
..            ...           ...           ...           ...
145           4.5           2.3           1.3           0.3
146           4.4           2.9           1.4           0.2
147           4.4           3.0           1.3           0.2
148           4.4           3.2           1.3           0.2
149           4.3           3.0           1.1           0.1

[150 rows x 4 columns]

In [ ]:
# Si la fila/columna no existe, nos dará error

#df.drop("Flor", axis = 1)

In [80]:
df["Clase2"] = df["Clase"] #creo nueva variable a partir de otra

df.head(3)

,Largo Sepalo,Ancho Sepalo,Largo Petalo,Ancho Petalo,Clase,Clase2
0,7.9,3.8,6.4,2.0,Iris-virginica,Iris-virginica
1,7.7,2.6,6.9,2.3,Iris-virginica,Iris-virginica
2,7.7,3.8,6.7,2.2,Iris-virginica,Iris-virginica

In [78]:
# Si queremos que la operación sea in-place podemos agregar el parametro

df.drop("Clase2", axis = 1, inplace = True)

KeyError: "['Clase2'] not found in axis"

In [79]:
df.head(3)

   Largo Sepalo  Ancho Sepalo  Largo Petalo  Ancho Petalo           Clase
0           7.9           3.8           6.4           2.0  Iris-virginica
1           7.7           2.6           6.9           2.3  Iris-virginica
2           7.7           3.8           6.7           2.2  Iris-virginica

In [81]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Valores únicos y frecuencias</h3>
  <hr class="nb-divider">

  <div class="nb-note" style="margin-top:.8rem;">
    <i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i>
    <span class="nb-note-text"><code class="ic">.value_counts()</code> ordena por frecuencia descendente por defecto. <code class="ic">.unique()</code> devuelve un array de NumPy con los valores en orden de aparición.</span>
  </div>
</div>

In [82]:
# .value_counts() Se usa para contar los valores únicos de las columnas (Series)

df["Clase"].value_counts()

Clase
Iris-virginica     50
Iris-versicolor    50
Iris-setosa        50
Name: count, dtype: int64

In [83]:
# Podemos "Normalizar" el resultado

df["Clase"].value_counts(normalize = True)

Clase
Iris-virginica     0.333333
Iris-versicolor    0.333333
Iris-setosa        0.333333
Name: proportion, dtype: float64

In [ ]:
# .unique() retorna un array con los valores únicos de las columnas
df["Clase"].unique()

In [84]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Filtros</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    Aplicar un operador de comparación sobre una columna devuelve una <strong>Serie booleana</strong> (<code class="ic">True</code>/<code class="ic">False</code>). Usar esa Serie como índice del DataFrame filtra las filas que cumplen la condición.
    Para combinar varios filtros usar <code class="ic">&</code> (y) y <code class="ic">|</code> (o), agrupando cada condición entre paréntesis <code class="ic">()</code>.
  </div>

</div>

In [85]:
# Para aplicar un filtro usamos los operadores de comparación

df["Largo Sepalo"] > 7

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: Largo Sepalo, Length: 150, dtype: bool

In [88]:
# Esto retorna una Serie con Verdaderos y Falsos
# Si quisieramos aplicar ese filtro al DataFrame hariamos un "indexing" con el operador

df[df["Largo Sepalo"] > 7] # así solo seleccionamos los True

# Esto nos retorna el DataFrame solo con las filas que cumplen la condición

SyntaxError: invalid syntax (2127560477.py, line 4)

In [91]:
# 20
# selecciona filas del DataFrame df donde el valor en la columna 'Largo Sepalo' es mayor que 7
# Ó el valor en la columna 'Ancho Petalo' es menor que 2.
# El operador | significa 'o' lógico.
df[(df['Largo Sepalo'] > 7) | (df['Ancho Petalo'] < 2)] #condiciones entre parémntesis, porque van a ser varias

,Largo Sepalo,Ancho Sepalo,Largo Petalo,Ancho Petalo,Clase,Clase2
0,7.9,3.8,6.4,2.0,Iris-virginica,Iris-virginica
1,7.7,2.6,6.9,2.3,Iris-virginica,Iris-virginica
2,7.7,3.8,6.7,2.2,Iris-virginica,Iris-virginica
3,7.7,2.8,6.7,2.0,Iris-virginica,Iris-virginica
4,7.7,3.0,6.1,2.3,Iris-virginica,Iris-virginica
...,...,...,...,...,...,...
145,4.5,2.3,1.3,0.3,Iris-setosa,Iris-setosa
146,4.4,2.9,1.4,0.2,Iris-setosa,Iris-setosa
147,4.4,3.0,1.3,0.2,Iris-setosa,Iris-setosa
148,4.4,3.2,1.3,0.2,Iris-setosa,Iris-setosa
149,4.3,3.0,1.1,0.1,Iris-setosa,Iris-setosa

In [94]:
# 21
# para aplicar más de un filtro
# El operador & significa 'y' lógico.


# selecciona filas del DataFrame df donde el valor en la columna 'Largo Sepalo' es mayor que 7
# Y el valor en la columna 'Ancho Petalo' es igual 2.
df[(df['Largo Sepalo'] > 7) & (df['Ancho Petalo'] == 2)]

,Largo Sepalo,Ancho Sepalo,Largo Petalo,Ancho Petalo,Clase,Clase2
0,7.9,3.8,6.4,2.0,Iris-virginica,Iris-virginica
3,7.7,2.8,6.7,2.0,Iris-virginica,Iris-virginica

In [ ]:
# Selecciona filas del DataFrame donde el valor en la columna `'Clase'` es igual a `'Iris-virginica'`
# Ó donde el valor en la columna `'Clase'` es igual a `'Iris-versicolor'`.
df[(df["Clase"] == "Iris-virginica") | (df["Clase"] == "Iris-versicolor")]

In [95]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Cambiar el tipo de datos</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    <code class="ic">.astype()</code> convierte el tipo de dato de una columna o varias a la vez. Los tipos más comunes son <code class="ic">int8</code>, <code class="ic">int64</code>, <code class="ic">float64</code>, <code class="ic">str</code>, <code class="ic">bool</code> y <code class="ic">category</code>.
    El tipo <code class="ic">category</code> es eficiente en memoria cuando una columna tiene pocos valores únicos repetidos.
  </div>

</div>

In [96]:
df = pd.DataFrame({"Nombre" : ["Gael", "Paola", "Maria", "Josue", "Martha", "Romero", "Sandra"],
                   "Edad" : [27, 28, 29, 28, 30, 30, 28]})

df["Residencia"] = ["Madrid", "Madrid", "Bilbao", "Madrid", "Madrid", "Zaragoza", "?"]

df

   Nombre  Edad Residencia
0    Gael    27     Madrid
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      7 non-null      object
 1   Edad        7 non-null      int64
 2   Residencia  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [102]:
# 22
# Modificar el tipo de dato de la columna "edad" a "int8"
df["Edad"] = df["Edad"].astype('int8')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      7 non-null      object
 1   Edad        7 non-null      int8
 2   Residencia  7 non-null      object
dtypes: int8(1), object(2)
memory usage: 251.0+ bytes

In [105]:
# 23
# Cambiar el tipo de dato de la columna "Nombre" a "category"
df["Nombre"] = df["Nombre"].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      7 non-null      category
 1   Edad        7 non-null      int8
 2   Residencia  7 non-null      object
dtypes: category(1), int8(1), object(1)
memory usage: 558.0+ bytes

In [106]:
# Ahora es tipo "category"

df["Nombre"]

0      Gael
1     Paola
2     Maria
3     Josue
4    Martha
5    Romero
6    Sandra
Name: Nombre, dtype: category
Categories (7, object): ['Gael', 'Josue', 'Maria', 'Martha', 'Paola', 'Romero', 'Sandra']

In [107]:
# Esta columna sigue siendo "object"

df["Residencia"]

0      Madrid
1      Madrid
2      Bilbao
3      Madrid
4      Madrid
5    Zaragoza
6           ?
Name: Residencia, dtype: object

In [108]:
# Cambiar 2 o más a la vez

df[["Nombre", "Residencia"]] = df[["Nombre", "Residencia"]].astype("category")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      7 non-null      category
 1   Edad        7 non-null      int8
 2   Residencia  7 non-null      category
dtypes: category(2), int8(1)
memory usage: 713.0 bytes

In [109]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Filtrado avanzado</h3>
  <hr class="nb-divider">
  <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;Método</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Descripción</th>
      </tr></thead>
<tbody>
  <tr><td><span class="tip"><code class="ic">.isin([val1, val2])</code>
    <span class="tt" style="max-width:400px;">
      Equivalente a múltiples condiciones OR sobre la misma columna. Más limpio y legible.
    </span>
  </span></td><td class="desc">Filtra filas cuyo valor esté en la lista</td></tr>

  <tr><td><span class="tip"><code class="ic">.between(a, b)</code>
    <span class="tt" style="max-width:400px;">
      Ambos extremos a y b están incluidos. Solo funciona en columnas numéricas.
    </span>
  </span></td><td class="desc">Filtra por rango <strong>[a, b]</strong> — ambos extremos incluidos</td></tr>

  <tr><td><span class="tip"><code class="ic">~</code>
    <span class="tt" style="max-width:400px;">
      El operador ~ invierte el booleano: True → False y viceversa. Equivale a NOT.
    </span>
  </span></td><td class="desc">Niega el filtro (NOT)</td></tr>

  <tr><td><span class="tip"><code class="ic">.duplicated()</code>
    <span class="tt" style="max-width:400px;top:auto;bottom:calc(100% + 6px);">
      No marca la primera aparición como duplicada, solo las repeticiones posteriores.
      <span style="position:absolute;top:100%;left:14px;border:5px solid transparent;border-top-color:#1e293b;"></span>
    </span>
  </span></td><td class="desc">Detecta filas con valores repetidos</td></tr>
</tbody>
    </table>
  </div>

</div>

In [110]:
# Filtramos sobre la misma columna

df[(df["Residencia"] == "Madrid") | (df["Residencia"] == "Bilbao")]

   Nombre  Edad Residencia
0    Gael    27     Madrid
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid

In [114]:
# 24
# El mismo resultado se puede lograr con: .isin()
df[(df["Residencia"].isin(["Madrid","Bilbao"]))]

   Nombre  Edad Residencia
0    Gael    27     Madrid
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid

In [115]:
# Seleccionamos todos los individuos cuya edad sea 28 o 30
df[df["Edad"].isin([30, 28])]

   Nombre  Edad Residencia
1   Paola    28     Madrid
3   Josue    28     Madrid
4  Martha    30     Madrid
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [118]:
# 25

# Si quisieramos filtrar por un rango, podemos usar: .between()
# Los dos extremos son incluidos
# Solo se puede usar en columnas númericas
df[df["Edad"].between(28, 30)]

   Nombre  Edad Residencia
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [120]:
# 26
# Con ~ podemos obtener el resultado opuesto:
df[~df["Edad"].between(28, 30)]

  Nombre  Edad Residencia
0   Gael    27     Madrid

In [121]:
# Si tenemos más de 1 condición debemos agruparlas con parentesis ()

df[(df["Edad"].isin([30, 28])) & (df["Residencia"] != "Madrid")]

   Nombre  Edad Residencia
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [ ]:
df

In [122]:
# Con .duplicated() vemos las filas que tengan valores repetidos, no muestra las primera apariciones

df[df["Edad"].duplicated()]

   Nombre  Edad Residencia
3   Josue    28     Madrid
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [123]:
df

   Nombre  Edad Residencia
0    Gael    27     Madrid
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [124]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Reemplazar elementos</h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    <code class="ic">.replace()</code> sustituye valores dentro de una Serie o DataFrame. Por defecto <strong>no es in-place</strong>. Acepta un valor simple, una lista o un diccionario como parámetro.
  </div>

</div>

In [125]:
# .replace() funciona similar a la función de cadenas de caracteres (datos categóricos)
# Por lo tanto debemos usar cat.rename_categories
# Estos cambios NO son in-place

df["Residencia"] = df["Residencia"].cat.rename_categories({"Madrid": "MADRID"})

In [126]:
df

   Nombre  Edad Residencia
0    Gael    27     MADRID
1   Paola    28     MADRID
2   Maria    29     Bilbao
3   Josue    28     MADRID
4  Martha    30     MADRID
5  Romero    30   Zaragoza
6  Sandra    28          ?

In [ ]:
# Para hacerlo inplace podemos asignarlo:

df["Residencia"] = df["Residencia"].replace("Madrid", "MADRID")

In [ ]:
df

In [127]:
# Podemos reemplazar "?" por un np.nan
# Esta es otra forma de sobreescribir la columna

df["Residencia"] = df["Residencia"].astype("str").replace("?", np.nan)

df

   Nombre  Edad Residencia
0    Gael    27     MADRID
1   Paola    28     MADRID
2   Maria    29     Bilbao
3   Josue    28     MADRID
4  Martha    30     MADRID
5  Romero    30   Zaragoza
6  Sandra    28        NaN

In [129]:
# .replace() puede tomar un diccionario como parametro
# El diccionario va a tener llaves y valores
# Lo que significa que cada vez que encuentre una llave en la columna lo va a sustituir por su valor

diccionario = {"Gael" : "Pedro",
               "Paola" : "Andrea"}

df["Nombre"].cat.rename_categories({"Gael": "Pedro", "Paola": "Andrea"})

0     Pedro
1    Andrea
2     Maria
3     Josue
4    Martha
5    Romero
6    Sandra
Name: Nombre, dtype: category
Categories (7, object): ['Pedro', 'Josue', 'Maria', 'Martha', 'Andrea', 'Romero', 'Sandra']

In [128]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Concatenación — <code class="ic" style="font-size:16px;">pd.concat()</code></h3>
  <hr class="nb-divider">
  <div class="grid2">
    <div class="card">
      <div class="card-title"><i class="ti ti-arrow-bar-down" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Vertical — axis=0</div>
      <div class="card-body">Apila DataFrames por filas. Si tienen las mismas columnas las agrupa automáticamente. Si tienen columnas distintas, rellena con <code class="ic">NaN</code>.</div>
    </div>
    <div class="card">
      <div class="card-title"><i class="ti ti-arrow-bar-right" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Horizontal — axis=1</div>
      <div class="card-body">Une DataFrames por columnas. Pueden tener distinto número de filas — las que no coincidan se rellenan con <code class="ic">NaN</code>.</div>
    </div>
  </div>

</div>

In [130]:
df1 = pd.DataFrame({"Columna_1" : ["A", "B"],
                    "Columna_2" : ["C", "D"]})

df2 = pd.DataFrame({"Columna_3" : ["E", "F", "G"],
                    "Columna_4" : ["G", "H", "I"]})

In [131]:
df1

  Columna_1 Columna_2
0         A         C
1         B         D

In [132]:
df2

  Columna_3 Columna_4
0         E         G
1         F         H
2         G         I

In [133]:
# 27
# Para concatenar horizontalmente hay que usar axis = 1
pd.concat([df1,df2],axis=1)

  Columna_1 Columna_2 Columna_3 Columna_4
0         A         C         E         G
1         B         D         F         H
2       NaN       NaN         G         I

In [135]:
# Usando un solo pd.concat() podemos concatenar varios DataFrames a la vez, incluso repetirlos

pd.concat([df1, df2, df2, df1], axis = 1)

,Columna_1,Columna_2,Columna_3,Columna_4,Columna_3,Columna_4,Columna_1,Columna_2
0,A,C,E,G,E,G,A,C
1,B,D,F,H,F,H,B,D
2,NaN,NaN,G,I,G,I,NaN,NaN

In [136]:
#Vertical
df1 = pd.DataFrame({"Columna_1" : ["A", "B", "1"],
                    "Columna_2" : ["C", "D", "2"]})

df2 = pd.DataFrame({"Columna_1" : ["E", "F"],
                    "Columna_2" : ["G", "H"]})

# Ambos tienen el mismo nombre en las columnas

In [137]:
df1

  Columna_1 Columna_2
0         A         C
1         B         D
2         1         2

In [138]:
df2

  Columna_1 Columna_2
0         E         G
1         F         H

In [139]:
# Como tienen el mismo nombre de columnas, pandas los agrupa automaticamente

pd.concat([df1, df2], axis = 0)

  Columna_1 Columna_2
0         A         C
1         B         D
2         1         2
0         E         G
1         F         H

In [140]:
df3 = pd.DataFrame({"Columna_1" : ["E", "F"],
                    "Columna_3" : ["G", "H"]})

df3

  Columna_1 Columna_3
0         E         G
1         F         H

In [141]:
# En este ejemplo los DataFrames tienen columnas diferentes

pd.concat([df1, df3], axis = 0)

# Por eso, pandas agrupa la columna en comun, y las que sean diferentes las llena con NaN's

  Columna_1 Columna_2 Columna_3
0         A         C       NaN
1         B         D       NaN
2         1         2       NaN
0         E       NaN         G
1         F       NaN         H

In [142]:
# Si nos fijamos, pandas incluso concatena los indices, para evitar este comportamiento podemos agregar otro parametro:

pd.concat([df1, df3], axis = 0, ignore_index = True)

  Columna_1 Columna_2 Columna_3
0         A         C       NaN
1         B         D       NaN
2         1         2       NaN
3         E       NaN         G
4         F       NaN         H

In [143]:
# @title {"run":"auto","vertical-output":true,"single-column":true,"display-mode":"form"}
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-title{font-size:20px;font-weight:600;color:#1E3A8A;margin:0 0 .9rem 0;letter-spacing:-.3px;}
  .nb-title-sm{font-size:17px;font-weight:600;color:#1E3A8A;margin:0 0 .8rem 0;}
  .nb-badge{font-size:11px;font-weight:500;color:#0F766E;background:#CCFBF1;padding:3px 10px;border-radius:20px;border:1px solid #99F6E4;letter-spacing:.4px;text-transform:uppercase;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.25rem;border:none;}
  .nb-divider-sm{height:1px;background:linear-gradient(90deg,#475569 0%,transparent 80%);margin-bottom:1rem;border:none;}
  .nb-body{color:#1e293b;font-size:14px;line-height:1.75;margin-bottom:1rem;}
  .nb-body p{margin:0 0 .7rem;}
  .nb-body-box{font-size:13.5px;color:#1e293b;line-height:1.7;margin-bottom:1rem;padding:10px 14px;background:#F8FAFF;border-left:3px solid #1E3A8A;border-radius:0 6px 6px 0;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  code.ic-g{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#F0FDF4;color:#0F766E;padding:2px 7px;border-radius:4px;border:1px solid #99F6E4;white-space:nowrap;}
  code.ic-a{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#FFF7ED;color:#92400E;padding:2px 7px;border-radius:4px;border:1px solid #FED7AA;white-space:nowrap;}
  .code-block{background:#0f172a;border-radius:8px;overflow:hidden;margin-top:.5rem;}
  .code-header{display:flex;align-items:center;justify-content:space-between;padding:7px 14px;background:#1e293b;border-bottom:1px solid #334155;}
  .code-lang{font-family:'Source Code Pro',monospace;font-size:11px;color:#64748b;letter-spacing:.5px;text-transform:uppercase;}
  .dots{display:flex;gap:5px;}.dot{width:9px;height:9px;border-radius:50%;}
  .dot-r{background:#ef4444;}.dot-y{background:#f59e0b;}.dot-g{background:#22c55e;}
  pre.cc{padding:14px 18px;font-family:'Source Code Pro',monospace;font-size:13px;line-height:1.7;color:#e2e8f0;margin:0;white-space:pre;}
  .kw{color:#7dd3fc;}.mod{color:#a5f3fc;}.al{color:#86efac;}.cm{color:#94A3B8;font-style:italic;}
  .fn{color:#c4b5fd;}.st{color:#86efac;}.num{color:#fcd34d;}.op{color:#f9a8d4;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .table-wrap{border-radius:8px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ref-table{width:100%;border-collapse:collapse;font-size:13px;}
  .ref-table thead tr{background:#1E3A8A;color:#fff;}
  .ref-table thead th{padding:10px 16px;text-align:left;font-weight:500;font-size:11px;letter-spacing:.8px;text-transform:uppercase;}
  .ref-table thead th:first-child{border-radius:8px 0 0 0;width:35%;}
  .ref-table thead th:last-child{border-radius:0 8px 0 0;}
  .ref-table tbody tr:nth-child(odd){background:#F8FAFF;}
  .ref-table tbody tr:nth-child(even){background:#fff;}
  .ref-table tbody tr:hover{background:#EFF6FF;}
  .ref-table tbody td{padding:9px 16px;border-bottom:.5px solid rgba(0,0,0,.06);color:#1e293b;vertical-align:middle;}
  .ref-table tbody tr:last-child td{border-bottom:none;}
  .ref-table tbody tr:last-child td:first-child{border-radius:0 0 0 8px;}
  .ref-table tbody tr:last-child td:last-child{border-radius:0 0 8px 0;}
  .desc{font-size:13px;color:#475569;line-height:1.5;}
  .desc strong{color:#1E3A8A;font-weight:600;}
  .tip{position:relative;display:inline-block;}
  .tip .tt{visibility:hidden;opacity:0;background:#1e293b;color:#e2e8f0;font-family:'DM Sans',sans-serif;font-size:12px;line-height:1.5;border-radius:6px;padding:7px 11px;position:absolute;z-index:999;left:0;top:calc(100% + 6px);white-space:normal;max-width:300px;box-shadow:0 4px 12px rgba(0,0,0,.2);transition:opacity .18s ease;pointer-events:none;}
  .tip .tt::before{content:'';position:absolute;bottom:100%;left:14px;border:5px solid transparent;border-bottom-color:#1e293b;}
  .tip:hover .tt{visibility:visible;opacity:1;}
  .hint{font-size:11px;color:#94A3B8;margin-top:.6rem;display:flex;align-items:center;gap:5px;}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:12px;}
  .card{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:10px;padding:1rem;}
  .card-title{font-size:11px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;margin-bottom:.6rem;padding-bottom:.5rem;border-bottom:.5px solid rgba(0,0,0,.07);}
  .card-body{font-size:13px;color:#1e293b;line-height:1.6;}
  .rb{display:inline-block;font-size:10px;font-weight:600;padding:2px 7px;border-radius:20px;vertical-align:middle;white-space:nowrap;margin-left:5px;}
  .rb-blue{background:#EFF6FF;color:#1E3A8A;border:1px solid #BFDBFE;}
  .rb-teal{background:#F0FDF4;color:#0F766E;border:1px solid #99F6E4;}
  .rb-amber{background:#FFF7ED;color:#92400E;border:1px solid #FED7AA;}
</style>

<div class="nb-cell">
  <h3 class="nb-title">Combinación — <code class="ic" style="font-size:16px;">pd.merge()</code></h3>
  <hr class="nb-divider">
  <div class="nb-body-box">
    <code class="ic">pd.merge()</code> une dos DataFrames que comparten una columna en común, similar a un <strong>JOIN de SQL</strong>. El parámetro <code class="ic">how</code> controla el tipo de unión.
  </div>
  <div class="table-wrap" style="overflow:visible;">
    <table class="ref-table">
      <thead><tr>
        <th><i class="ti ti-function"></i> &nbsp;how</th>
        <th><i class="ti ti-align-left"></i> &nbsp;Comportamiento</th>
      </tr></thead>
      <tbody>
        <tr><td><span class="tip"><code class="ic">"inner"</code><span class="tt">Solo las filas donde la clave aparece en AMBOS DataFrames. Es el valor por defecto.</span></span> <span class="rb rb-blue">defecto</span></td><td class="desc">Solo filas con clave en <strong>ambos</strong> DataFrames</td></tr>
        <tr><td><span class="tip"><code class="ic">"outer"</code><span class="tt">Todas las filas de ambos DataFrames. Las que no tienen par se rellenan con NaN.</span></span></td><td class="desc">Todas las filas, rellena con <code class="ic">NaN</code> donde no hay par</td></tr>
        <tr><td><span class="tip"><code class="ic">"left"</code><span class="tt">Todas las filas del DataFrame izquierdo. Si no hay par en el derecho → NaN.</span></span></td><td class="desc">Todas las filas del DataFrame <strong>izquierdo</strong></td></tr>
        <tr><td><span class="tip"><code class="ic">"right"</code><span class="tt">Todas las filas del DataFrame derecho. Si no hay par en el izquierdo → NaN.</span></span></td><td class="desc">Todas las filas del DataFrame <strong>derecho</strong></td></tr>
      </tbody>
    </table>
  </div>

</div>

In [144]:
df1 = pd.DataFrame({"Nombre" : ["Gael", "Paola", "Maria", "Josue", "Martha", "Romero", "Sandra"],
                    "Edad" : [27, 28, 29, 28, 30, 30, 28]})
df1

   Nombre  Edad
0    Gael    27
1   Paola    28
2   Maria    29
3   Josue    28
4  Martha    30
5  Romero    30
6  Sandra    28

In [146]:
df2 = pd.DataFrame({"Nombre" : ["Gael", "Paola", "Maria", "Josue", "Martha", "Romero", "Sandro"],
                    "Residencia" : ["Madrid", "Madrid", "Bilbao", "Madrid", "Madrid", "Zaragoza", "Sevilla"]})
df2

   Nombre Residencia
0    Gael     Madrid
1   Paola     Madrid
2   Maria     Bilbao
3   Josue     Madrid
4  Martha     Madrid
5  Romero   Zaragoza
6  Sandro    Sevilla

In [147]:
# pd.merge() Une dos DataFrames que tengan una columna en común:
# Por defecto "how" es "inner"

pd.merge(left = df1, right = df2, left_on = "Nombre", right_on = "Nombre", how = "inner")

   Nombre  Edad Residencia
0    Gael    27     Madrid
1   Paola    28     Madrid
2   Maria    29     Bilbao
3   Josue    28     Madrid
4  Martha    30     Madrid
5  Romero    30   Zaragoza

In [148]:
pd.merge(left = df1, right = df2, left_on = "Nombre", right_on = "Nombre", how = "outer")

   Nombre  Edad Residencia
0    Gael  27.0     Madrid
1   Josue  28.0     Madrid
2   Maria  29.0     Bilbao
3  Martha  30.0     Madrid
4   Paola  28.0     Madrid
5  Romero  30.0   Zaragoza
6  Sandra  28.0        NaN
7  Sandro   NaN    Sevilla

In [149]:
# pd.merge() usando otros parámetros:
# Nota: esto solo funciona si ambos DataFrames tienen la columna con el mismo nombre

pd.merge(left = df1, right = df2, on = "Nombre", how = "outer")

   Nombre  Edad Residencia
0    Gael  27.0     Madrid
1   Josue  28.0     Madrid
2   Maria  29.0     Bilbao
3  Martha  30.0     Madrid
4   Paola  28.0     Madrid
5  Romero  30.0   Zaragoza
6  Sandra  28.0        NaN
7  Sandro   NaN    Sevilla